### ISSUE TITLE
missing API docs

### ISSUE THREAD

**Issue by flecno** [luft-jetzt/luft-app#83]
Moin,
I want to use your API to dump some station values in my influxdb. The linked https://luft.jetzt/api/doc is not online anymore. Where can I find the API docs? :)

**Comment by maltehuebner** [comment]
Thank you for your report. It should be fixed in #84 and is now deployed.

I’ll work on some more improvements for api doc in the next days, but it should work so far ;-)

**Comment by BirgerK** [comment]
Hi there, when opening the API docs it returns a 404. :(

**Comment by trych** [comment]
The API docs still could not be opened. Would be really helpful, if there was *any* info on how to use the API.

**Comment by Sabi89129** [comment]
Hi Malte! Is it planned to solve this bug? I would really appreciate using the API.

**Comment by Dtrieb** [comment]
Still nothing happened!?

**Comment by timluedtke** [comment]
bump - https://luft.jetzt/api/doc & https://luft.jetzt/api/ still give 404

**Comment by maltehuebner** [comment]
Thank you for your patience - I had another flash of inspiration today and solved the problem. The Api documentation is now available at https://luft.jetzt/api/doc.

What was the problem? I noticed today that the 404 error message is obviously not delivered by the Symfony application and does not occur on my local development system either. The solution to the puzzle was the nginx configuration of Plesk, which wants to cache Word documents, among other things.

And /api/doc unfortunately matches the regular expression that searches for file extensions to be cached.
